### ISSUE TITLE
Shield Shield I2C

### ISSUE THREAD

**Issue by technobly** [spark/shields#28]
I2C pins are not available where they are needed for Arduino Shields, and new Arduinos have an extended pin set also not supported by the current Shield Shield.  There's probably a lot that can be done here for a more usable v2.0 Shield Shield.

```
Currently

Arduino   Spark Core  Shield Shield
A4 (SDA)  D0 (SDA)    D3
A5 (SCL)  D1 (SCL)    D5

* Arduino Leonardo also has dedicated SDA, SCL pins now
```

**Comment by mohitbhoite** [comment]
dedicated mosfets for I2C FTW
