### ISSUE TITLE
Threads in OpenOCD

### ISSUE THREAD

**Issue by hackrid** [spark/shields#51]
Hi,

i recently found your wiki entry https://github.com/spark/shields/wiki/Viewing-threads-in-openocd

I was hoping to get OpenOCD with FreeRTOS Thread Awareness working but no success.

the recent versions of OpenOCD do not provide *.cpu files as stated in your wiki.

I'm trying to start openOCD the following way, but it fails:
```
openocd -f board/stm32429i_eval_stlink.cfg  -c "-rtos auto" 
invalid command name "-rtos"
```

any hints on this problem?

**Comment by m-mcgowan** [comment]
I'm using openOCD with FreeRTOS. I launch using this command line
```
openocd -f interface/ftdi/particle-ftdi.cfg -f target/stm32f2x.cfg -c "stm32f2x.cpu configure -rtos auto" &
```

**Comment by hackrid** [comment]
thanks for your attention on this.

I got it working with the following command line:
`-f board/stm32429i_eval_stlink.cfg -c “$_TARGETNAME configure -rtos auto”`


how is your impression using OpenOCD with Thread Awareness? I experience a horrible single stepping speed since the back traces of the individual threads are built up every time....

**Comment by m-mcgowan** [comment]
It's not as fast as debugging a local executable but it's workable - single step times no more than 1 second, I'd guess, probably less.
